### ISSUE TITLE
Release it on PyPi

### ISSUE THREAD

**Issue by b3nab** [vtr0n/TelegramTUI#36]
Please,
create a python distribution package and upload it to the Python Package Index [PyPI](https://pypi.org) so everyone can just install it with `pip` using this command:

``` sh
pip install telegramtui
```

and then use it with:

```sh
telegramtui # or
telegram-tui # or
telegram-cli # or whatever you want

**Comment by vtr0n** [comment]
Thanks for the idea.
Closed #41
